/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const ApiResourceModel: typeof import('./src/models/ApiResourceModel')['ApiResourceModel']
  const AppIndexedDBService: typeof import('./src/services/indexed_db')['AppIndexedDBService']
  const AppIndexedDBStorage: typeof import('./src/services/app_indexed_db_storage')['AppIndexedDBStorage']
  const AppLocalStorage: typeof import('./src/services/AppLocalStorage')['default']
  const AppLogger: typeof import('./src/utils/logger')['AppLogger']
  const AppSessionStorage: typeof import('./src/services/AppSessionStorage')['default']
  const AppStorageService: typeof import('./src/services/app_storage_service')['AppStorageService']
  const AppUtils: typeof import('./src/utils/index')['AppUtils']
  const ApplicationModel: typeof import('./src/modules/applications/models/application_model')['ApplicationModel']
  const DateTime: typeof import('./src/utils/luxon')['DateTime']
  const EffectScope: typeof import('vue')['EffectScope']
  const GenericStoreService: typeof import('./src/services/generic_store_service')['GenericStoreService']
  const MachineModel: typeof import('./src/modules/machine/models/machine-model')['MachineModel']
  const OperatorModel: typeof import('./src/modules/operator/models/operator-model')['OperatorModel']
  const OperatorSalaryModel: typeof import('./src/modules/operator-salary/models/operator-salary-model')['OperatorSalaryModel']
  const PermissionModel: typeof import('./src/modules/permissions/models/permission_model')['PermissionModel']
  const RoleModel: typeof import('./src/modules/roles/models/role_model')['RoleModel']
  const SessionModel: typeof import('./src/modules/authentication/models/session_model')['SessionModel']
  const UserModel: typeof import('./src/modules/users/models/user_model')['UserModel']
  const acceptHMRUpdate: typeof import('pinia')['acceptHMRUpdate']
  const apiRouteInterface: typeof import('./src/api/interfaces/api_route_interface')['default']
  const appIndexedDbStorage: typeof import('./src/services/app_indexed_db_storage')['default']
  const appLogger: typeof import('./src/utils/logger')['appLogger']
  const appRoutes: typeof import('./src/router/routes')['appRoutes']
  const asyncComputed: typeof import('@vueuse/core')['asyncComputed']
  const autoResetRef: typeof import('@vueuse/core')['autoResetRef']
  const computed: typeof import('vue')['computed']
  const computedAsync: typeof import('@vueuse/core')['computedAsync']
  const computedEager: typeof import('@vueuse/core')['computedEager']
  const computedInject: typeof import('@vueuse/core')['computedInject']
  const computedWithControl: typeof import('@vueuse/core')['computedWithControl']
  const controlledComputed: typeof import('@vueuse/core')['controlledComputed']
  const controlledRef: typeof import('@vueuse/core')['controlledRef']
  const createApp: typeof import('vue')['createApp']
  const createEventHook: typeof import('@vueuse/core')['createEventHook']
  const createGenericProjection: typeof import('@vueuse/math')['createGenericProjection']
  const createGlobalState: typeof import('@vueuse/core')['createGlobalState']
  const createInjectionState: typeof import('@vueuse/core')['createInjectionState']
  const createLogger: typeof import('./src/utils/logger')['createLogger']
  const createPinia: typeof import('pinia')['createPinia']
  const createProjection: typeof import('@vueuse/math')['createProjection']
  const createReactiveFn: typeof import('@vueuse/core')['createReactiveFn']
  const createRef: typeof import('@vueuse/core')['createRef']
  const createReusableTemplate: typeof import('@vueuse/core')['createReusableTemplate']
  const createRoutes: typeof import('./src/utils/routes')['createRoutes']
  const createSharedComposable: typeof import('@vueuse/core')['createSharedComposable']
  const createTemplatePromise: typeof import('@vueuse/core')['createTemplatePromise']
  const createUnrefFn: typeof import('@vueuse/core')['createUnrefFn']
  const customRef: typeof import('vue')['customRef']
  const debouncedRef: typeof import('@vueuse/core')['debouncedRef']
  const debouncedWatch: typeof import('@vueuse/core')['debouncedWatch']
  const defineAsyncComponent: typeof import('vue')['defineAsyncComponent']
  const defineComponent: typeof import('vue')['defineComponent']
  const defineStore: typeof import('pinia')['defineStore']
  const eagerComputed: typeof import('@vueuse/core')['eagerComputed']
  const effectScope: typeof import('vue')['effectScope']
  const extendRef: typeof import('@vueuse/core')['extendRef']
  const extractMonthAndYear: typeof import('./src/utils/formatDate')['extractMonthAndYear']
  const formIsValid: typeof import('./src/utils/form_is_valid')['formIsValid']
  const formatPhoneWithSpaces: typeof import('./src/utils/remove_white_space')['formatPhoneWithSpaces']
  const getActivePinia: typeof import('pinia')['getActivePinia']
  const getCurrentInstance: typeof import('vue')['getCurrentInstance']
  const getCurrentScope: typeof import('vue')['getCurrentScope']
  const getCurrentWatcher: typeof import('vue')['getCurrentWatcher']
  const globalStoreDefinition: typeof import('./src/stores/global/definition')['globalStoreDefinition']
  const guestRoutes: typeof import('./src/router/routes')['guestRoutes']
  const h: typeof import('vue')['h']
  const hexToRgba: typeof import('./src/utils/hex_to_rgba')['hexToRgba']
  const ignorableWatch: typeof import('@vueuse/core')['ignorableWatch']
  const inject: typeof import('vue')['inject']
  const injectLocal: typeof import('@vueuse/core')['injectLocal']
  const isDefined: typeof import('@vueuse/core')['isDefined']
  const isProxy: typeof import('vue')['isProxy']
  const isReactive: typeof import('vue')['isReactive']
  const isReadonly: typeof import('vue')['isReadonly']
  const isRef: typeof import('vue')['isRef']
  const isShallow: typeof import('vue')['isShallow']
  const logicAnd: typeof import('@vueuse/math')['logicAnd']
  const logicNot: typeof import('@vueuse/math')['logicNot']
  const logicOr: typeof import('@vueuse/math')['logicOr']
  const luxonFormats: typeof import('./src/utils/luxon')['luxonFormats']
  const machineStoreDefinition: typeof import('./src/modules/machine/store/definition')['machineStoreDefinition']
  const makeDestructurable: typeof import('@vueuse/core')['makeDestructurable']
  const mapActions: typeof import('pinia')['mapActions']
  const mapGetters: typeof import('pinia')['mapGetters']
  const mapState: typeof import('pinia')['mapState']
  const mapStores: typeof import('pinia')['mapStores']
  const mapWritableState: typeof import('pinia')['mapWritableState']
  const markRaw: typeof import('vue')['markRaw']
  const nextTick: typeof import('vue')['nextTick']
  const numberFormatter: typeof import('./src/utils/number_formatter')['numberFormatter']
  const onActivated: typeof import('vue')['onActivated']
  const onBeforeMount: typeof import('vue')['onBeforeMount']
  const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
  const onBeforeUpdate: typeof import('vue')['onBeforeUpdate']
  const onClickOutside: typeof import('@vueuse/core')['onClickOutside']
  const onDeactivated: typeof import('vue')['onDeactivated']
  const onElementRemoval: typeof import('@vueuse/core')['onElementRemoval']
  const onErrorCaptured: typeof import('vue')['onErrorCaptured']
  const onKeyStroke: typeof import('@vueuse/core')['onKeyStroke']
  const onLongPress: typeof import('@vueuse/core')['onLongPress']
  const onMounted: typeof import('vue')['onMounted']
  const onRenderTracked: typeof import('vue')['onRenderTracked']
  const onRenderTriggered: typeof import('vue')['onRenderTriggered']
  const onScopeDispose: typeof import('vue')['onScopeDispose']
  const onServerPrefetch: typeof import('vue')['onServerPrefetch']
  const onStartTyping: typeof import('@vueuse/core')['onStartTyping']
  const onUnmounted: typeof import('vue')['onUnmounted']
  const onUpdated: typeof import('vue')['onUpdated']
  const onWatcherCleanup: typeof import('vue')['onWatcherCleanup']
  const operatorSalaryStoreDefinition: typeof import('./src/modules/operator-salary/store/definition')['operatorSalaryStoreDefinition']
  const operatorStoreDefinition: typeof import('./src/modules/operator/store/definition')['operatorStoreDefinition']
  const pausableWatch: typeof import('@vueuse/core')['pausableWatch']
  const permissionStoreDefinition: typeof import('./src/modules/permissions/store/index')['permissionStoreDefinition']
  const provide: typeof import('vue')['provide']
  const provideLocal: typeof import('@vueuse/core')['provideLocal']
  const reactify: typeof import('@vueuse/core')['reactify']
  const reactifyObject: typeof import('@vueuse/core')['reactifyObject']
  const reactive: typeof import('vue')['reactive']
  const reactiveComputed: typeof import('@vueuse/core')['reactiveComputed']
  const reactiveOmit: typeof import('@vueuse/core')['reactiveOmit']
  const reactivePick: typeof import('@vueuse/core')['reactivePick']
  const readonly: typeof import('vue')['readonly']
  const ref: typeof import('vue')['ref']
  const refAutoReset: typeof import('@vueuse/core')['refAutoReset']
  const refDebounced: typeof import('@vueuse/core')['refDebounced']
  const refDefault: typeof import('@vueuse/core')['refDefault']
  const refThrottled: typeof import('@vueuse/core')['refThrottled']
  const refWithControl: typeof import('@vueuse/core')['refWithControl']
  const registerPlugins: typeof import('./src/router/index')['registerPlugins']
  const removeWhitespace: typeof import('./src/utils/remove_white_space')['removeWhitespace']
  const resolveComponent: typeof import('vue')['resolveComponent']
  const resolveRef: typeof import('@vueuse/core')['resolveRef']
  const resolveUnref: typeof import('@vueuse/core')['resolveUnref']
  const roleStoreDefinition: typeof import('./src/modules/roles/store/definition')['roleStoreDefinition']
  const router: typeof import('./src/router/index')['default']
  const routes: typeof import('./src/router/routes')['default']
  const sessionInterface: typeof import('./src/modules/authentication/login/interfaces/session_interface')['default']
  const sessionModel: typeof import('./src/modules/authentication/login/models/session_model')['default']
  const setActivePinia: typeof import('pinia')['setActivePinia']
  const setMapStoreSuffix: typeof import('pinia')['setMapStoreSuffix']
  const shallowReactive: typeof import('vue')['shallowReactive']
  const shallowReadonly: typeof import('vue')['shallowReadonly']
  const shallowRef: typeof import('vue')['shallowRef']
  const showAlert: typeof import('./src/utils/show_alert')['showAlert']
  const starter: typeof import('./src/router/starter')['default']
  const storeToRefs: typeof import('pinia')['storeToRefs']
  const syncRef: typeof import('@vueuse/core')['syncRef']
  const syncRefs: typeof import('@vueuse/core')['syncRefs']
  const templateRef: typeof import('@vueuse/core')['templateRef']
  const throttledRef: typeof import('@vueuse/core')['throttledRef']
  const throttledWatch: typeof import('@vueuse/core')['throttledWatch']
  const toRaw: typeof import('vue')['toRaw']
  const toReactive: typeof import('@vueuse/core')['toReactive']
  const toRef: typeof import('vue')['toRef']
  const toRefs: typeof import('vue')['toRefs']
  const toValue: typeof import('vue')['toValue']
  const toast: typeof import('./src/utils/toast')['toast']
  const triggerRef: typeof import('vue')['triggerRef']
  const tryOnBeforeMount: typeof import('@vueuse/core')['tryOnBeforeMount']
  const tryOnBeforeUnmount: typeof import('@vueuse/core')['tryOnBeforeUnmount']
  const tryOnMounted: typeof import('@vueuse/core')['tryOnMounted']
  const tryOnScopeDispose: typeof import('@vueuse/core')['tryOnScopeDispose']
  const tryOnUnmounted: typeof import('@vueuse/core')['tryOnUnmounted']
  const unref: typeof import('vue')['unref']
  const unrefElement: typeof import('@vueuse/core')['unrefElement']
  const until: typeof import('@vueuse/core')['until']
  const useAbs: typeof import('@vueuse/math')['useAbs']
  const useActiveElement: typeof import('@vueuse/core')['useActiveElement']
  const useAnimate: typeof import('@vueuse/core')['useAnimate']
  const useArrayDifference: typeof import('@vueuse/core')['useArrayDifference']
  const useArrayEvery: typeof import('@vueuse/core')['useArrayEvery']
  const useArrayFilter: typeof import('@vueuse/core')['useArrayFilter']
  const useArrayFind: typeof import('@vueuse/core')['useArrayFind']
  const useArrayFindIndex: typeof import('@vueuse/core')['useArrayFindIndex']
  const useArrayFindLast: typeof import('@vueuse/core')['useArrayFindLast']
  const useArrayIncludes: typeof import('@vueuse/core')['useArrayIncludes']
  const useArrayJoin: typeof import('@vueuse/core')['useArrayJoin']
  const useArrayMap: typeof import('@vueuse/core')['useArrayMap']
  const useArrayReduce: typeof import('@vueuse/core')['useArrayReduce']
  const useArraySome: typeof import('@vueuse/core')['useArraySome']
  const useArrayUnique: typeof import('@vueuse/core')['useArrayUnique']
  const useAsyncQueue: typeof import('@vueuse/core')['useAsyncQueue']
  const useAsyncState: typeof import('@vueuse/core')['useAsyncState']
  const useAttrs: typeof import('vue')['useAttrs']
  const useAverage: typeof import('@vueuse/math')['useAverage']
  const useBase64: typeof import('@vueuse/core')['useBase64']
  const useBattery: typeof import('@vueuse/core')['useBattery']
  const useBluetooth: typeof import('@vueuse/core')['useBluetooth']
  const useBreakpoints: typeof import('@vueuse/core')['useBreakpoints']
  const useBroadcastChannel: typeof import('@vueuse/core')['useBroadcastChannel']
  const useBrowserLocation: typeof import('@vueuse/core')['useBrowserLocation']
  const useCached: typeof import('@vueuse/core')['useCached']
  const useCeil: typeof import('@vueuse/math')['useCeil']
  const useClamp: typeof import('@vueuse/math')['useClamp']
  const useClipboard: typeof import('@vueuse/core')['useClipboard']
  const useClipboardItems: typeof import('@vueuse/core')['useClipboardItems']
  const useCloned: typeof import('@vueuse/core')['useCloned']
  const useColorMode: typeof import('@vueuse/core')['useColorMode']
  const useConfirmDialog: typeof import('@vueuse/core')['useConfirmDialog']
  const useCountdown: typeof import('@vueuse/core')['useCountdown']
  const useCounter: typeof import('@vueuse/core')['useCounter']
  const useCssModule: typeof import('vue')['useCssModule']
  const useCssVar: typeof import('@vueuse/core')['useCssVar']
  const useCssVars: typeof import('vue')['useCssVars']
  const useCurrentElement: typeof import('@vueuse/core')['useCurrentElement']
  const useCycleList: typeof import('@vueuse/core')['useCycleList']
  const useDark: typeof import('@vueuse/core')['useDark']
  const useDateFormat: typeof import('@vueuse/core')['useDateFormat']
  const useDebounce: typeof import('@vueuse/core')['useDebounce']
  const useDebounceFn: typeof import('@vueuse/core')['useDebounceFn']
  const useDebouncedRefHistory: typeof import('@vueuse/core')['useDebouncedRefHistory']
  const useDeviceMotion: typeof import('@vueuse/core')['useDeviceMotion']
  const useDeviceOrientation: typeof import('@vueuse/core')['useDeviceOrientation']
  const useDevicePixelRatio: typeof import('@vueuse/core')['useDevicePixelRatio']
  const useDevicesList: typeof import('@vueuse/core')['useDevicesList']
  const useDisplayMedia: typeof import('@vueuse/core')['useDisplayMedia']
  const useDocumentVisibility: typeof import('@vueuse/core')['useDocumentVisibility']
  const useDraggable: typeof import('@vueuse/core')['useDraggable']
  const useDropZone: typeof import('@vueuse/core')['useDropZone']
  const useElementBounding: typeof import('@vueuse/core')['useElementBounding']
  const useElementByPoint: typeof import('@vueuse/core')['useElementByPoint']
  const useElementHover: typeof import('@vueuse/core')['useElementHover']
  const useElementSize: typeof import('@vueuse/core')['useElementSize']
  const useElementVisibility: typeof import('@vueuse/core')['useElementVisibility']
  const useEventBus: typeof import('@vueuse/core')['useEventBus']
  const useEventListener: typeof import('@vueuse/core')['useEventListener']
  const useEventSource: typeof import('@vueuse/core')['useEventSource']
  const useEyeDropper: typeof import('@vueuse/core')['useEyeDropper']
  const useFavicon: typeof import('@vueuse/core')['useFavicon']
  const useFetch: typeof import('@vueuse/core')['useFetch']
  const useFileDialog: typeof import('@vueuse/core')['useFileDialog']
  const useFileSystemAccess: typeof import('@vueuse/core')['useFileSystemAccess']
  const useFloor: typeof import('@vueuse/math')['useFloor']
  const useFocus: typeof import('@vueuse/core')['useFocus']
  const useFocusWithin: typeof import('@vueuse/core')['useFocusWithin']
  const useFps: typeof import('@vueuse/core')['useFps']
  const useFullscreen: typeof import('@vueuse/core')['useFullscreen']
  const useGamepad: typeof import('@vueuse/core')['useGamepad']
  const useGeolocation: typeof import('@vueuse/core')['useGeolocation']
  const useGlobalStore: typeof import('./src/stores/global/index')['useGlobalStore']
  const useI18n: typeof import('vue-i18n')['useI18n']
  const useId: typeof import('vue')['useId']
  const useIdle: typeof import('@vueuse/core')['useIdle']
  const useImage: typeof import('@vueuse/core')['useImage']
  const useInfiniteScroll: typeof import('@vueuse/core')['useInfiniteScroll']
  const useInitializedGlobalStore: typeof import('./src/stores/global/index')['useInitializedGlobalStore']
  const useInitializedMachineStore: typeof import('./src/modules/machine/store/index')['useInitializedMachineStore']
  const useInitializedOperatorSalaryStore: typeof import('./src/modules/operator-salary/store/index')['useInitializedOperatorSalaryStore']
  const useInitializedOperatorStore: typeof import('./src/modules/operator/store/index')['useInitializedOperatorStore']
  const useInitializedPermissionStore: typeof import('./src/modules/permissions/store/index')['useInitializedPermissionStore']
  const useInitializedRoleStore: typeof import('./src/modules/roles/store/index')['useInitializedRoleStore']
  const useInitializedUserStore: typeof import('./src/modules/users/store/index')['useInitializedUserStore']
  const useIntersectionObserver: typeof import('@vueuse/core')['useIntersectionObserver']
  const useInterval: typeof import('@vueuse/core')['useInterval']
  const useIntervalFn: typeof import('@vueuse/core')['useIntervalFn']
  const useKeyModifier: typeof import('@vueuse/core')['useKeyModifier']
  const useLastChanged: typeof import('@vueuse/core')['useLastChanged']
  const useLocalStorage: typeof import('@vueuse/core')['useLocalStorage']
  const useMagicKeys: typeof import('@vueuse/core')['useMagicKeys']
  const useManualRefHistory: typeof import('@vueuse/core')['useManualRefHistory']
  const useMath: typeof import('@vueuse/math')['useMath']
  const useMax: typeof import('@vueuse/math')['useMax']
  const useMediaControls: typeof import('@vueuse/core')['useMediaControls']
  const useMediaQuery: typeof import('@vueuse/core')['useMediaQuery']
  const useMemoize: typeof import('@vueuse/core')['useMemoize']
  const useMemory: typeof import('@vueuse/core')['useMemory']
  const useMin: typeof import('@vueuse/math')['useMin']
  const useModel: typeof import('vue')['useModel']
  const useMounted: typeof import('@vueuse/core')['useMounted']
  const useMouse: typeof import('@vueuse/core')['useMouse']
  const useMouseInElement: typeof import('@vueuse/core')['useMouseInElement']
  const useMousePressed: typeof import('@vueuse/core')['useMousePressed']
  const useMutationObserver: typeof import('@vueuse/core')['useMutationObserver']
  const useNavigatorLanguage: typeof import('@vueuse/core')['useNavigatorLanguage']
  const useNetwork: typeof import('@vueuse/core')['useNetwork']
  const useNow: typeof import('@vueuse/core')['useNow']
  const useObjectUrl: typeof import('@vueuse/core')['useObjectUrl']
  const useOffsetPagination: typeof import('@vueuse/core')['useOffsetPagination']
  const useOnline: typeof import('@vueuse/core')['useOnline']
  const usePageLeave: typeof import('@vueuse/core')['usePageLeave']
  const useParallax: typeof import('@vueuse/core')['useParallax']
  const useParentElement: typeof import('@vueuse/core')['useParentElement']
  const usePerformanceObserver: typeof import('@vueuse/core')['usePerformanceObserver']
  const usePermission: typeof import('@vueuse/core')['usePermission']
  const usePointer: typeof import('@vueuse/core')['usePointer']
  const usePointerLock: typeof import('@vueuse/core')['usePointerLock']
  const usePointerSwipe: typeof import('@vueuse/core')['usePointerSwipe']
  const usePrecision: typeof import('@vueuse/math')['usePrecision']
  const usePreferredColorScheme: typeof import('@vueuse/core')['usePreferredColorScheme']
  const usePreferredContrast: typeof import('@vueuse/core')['usePreferredContrast']
  const usePreferredDark: typeof import('@vueuse/core')['usePreferredDark']
  const usePreferredLanguages: typeof import('@vueuse/core')['usePreferredLanguages']
  const usePreferredReducedMotion: typeof import('@vueuse/core')['usePreferredReducedMotion']
  const usePreferredReducedTransparency: typeof import('@vueuse/core')['usePreferredReducedTransparency']
  const usePrevious: typeof import('@vueuse/core')['usePrevious']
  const useProjection: typeof import('@vueuse/math')['useProjection']
  const useRafFn: typeof import('@vueuse/core')['useRafFn']
  const useRefHistory: typeof import('@vueuse/core')['useRefHistory']
  const useResizeObserver: typeof import('@vueuse/core')['useResizeObserver']
  const useRound: typeof import('@vueuse/math')['useRound']
  const useSSRWidth: typeof import('@vueuse/core')['useSSRWidth']
  const useScreenOrientation: typeof import('@vueuse/core')['useScreenOrientation']
  const useScreenSafeArea: typeof import('@vueuse/core')['useScreenSafeArea']
  const useScriptTag: typeof import('@vueuse/core')['useScriptTag']
  const useScroll: typeof import('@vueuse/core')['useScroll']
  const useScrollLock: typeof import('@vueuse/core')['useScrollLock']
  const useSessionStorage: typeof import('@vueuse/core')['useSessionStorage']
  const useShare: typeof import('@vueuse/core')['useShare']
  const useSlots: typeof import('vue')['useSlots']
  const useSorted: typeof import('@vueuse/core')['useSorted']
  const useSpeechRecognition: typeof import('@vueuse/core')['useSpeechRecognition']
  const useSpeechSynthesis: typeof import('@vueuse/core')['useSpeechSynthesis']
  const useStepper: typeof import('@vueuse/core')['useStepper']
  const useStorage: typeof import('@vueuse/core')['useStorage']
  const useStorageAsync: typeof import('@vueuse/core')['useStorageAsync']
  const useStyleTag: typeof import('@vueuse/core')['useStyleTag']
  const useSum: typeof import('@vueuse/math')['useSum']
  const useSupported: typeof import('@vueuse/core')['useSupported']
  const useSwipe: typeof import('@vueuse/core')['useSwipe']
  const useTemplateRef: typeof import('vue')['useTemplateRef']
  const useTemplateRefsList: typeof import('@vueuse/core')['useTemplateRefsList']
  const useTextDirection: typeof import('@vueuse/core')['useTextDirection']
  const useTextSelection: typeof import('@vueuse/core')['useTextSelection']
  const useTextareaAutosize: typeof import('@vueuse/core')['useTextareaAutosize']
  const useThrottle: typeof import('@vueuse/core')['useThrottle']
  const useThrottleFn: typeof import('@vueuse/core')['useThrottleFn']
  const useThrottledRefHistory: typeof import('@vueuse/core')['useThrottledRefHistory']
  const useTimeAgo: typeof import('@vueuse/core')['useTimeAgo']
  const useTimeAgoIntl: typeof import('@vueuse/core')['useTimeAgoIntl']
  const useTimeout: typeof import('@vueuse/core')['useTimeout']
  const useTimeoutFn: typeof import('@vueuse/core')['useTimeoutFn']
  const useTimeoutPoll: typeof import('@vueuse/core')['useTimeoutPoll']
  const useTimestamp: typeof import('@vueuse/core')['useTimestamp']
  const useTitle: typeof import('@vueuse/core')['useTitle']
  const useToNumber: typeof import('@vueuse/core')['useToNumber']
  const useToString: typeof import('@vueuse/core')['useToString']
  const useToggle: typeof import('@vueuse/core')['useToggle']
  const useTransition: typeof import('@vueuse/core')['useTransition']
  const useTrunc: typeof import('@vueuse/math')['useTrunc']
  const useUrlSearchParams: typeof import('@vueuse/core')['useUrlSearchParams']
  const useUserMedia: typeof import('@vueuse/core')['useUserMedia']
  const useVModel: typeof import('@vueuse/core')['useVModel']
  const useVModels: typeof import('@vueuse/core')['useVModels']
  const useVibrate: typeof import('@vueuse/core')['useVibrate']
  const useVirtualList: typeof import('@vueuse/core')['useVirtualList']
  const useWakeLock: typeof import('@vueuse/core')['useWakeLock']
  const useWebNotification: typeof import('@vueuse/core')['useWebNotification']
  const useWebSocket: typeof import('@vueuse/core')['useWebSocket']
  const useWebWorker: typeof import('@vueuse/core')['useWebWorker']
  const useWebWorkerFn: typeof import('@vueuse/core')['useWebWorkerFn']
  const useWindowFocus: typeof import('@vueuse/core')['useWindowFocus']
  const useWindowScroll: typeof import('@vueuse/core')['useWindowScroll']
  const useWindowSize: typeof import('@vueuse/core')['useWindowSize']
  const userStoreDefinition: typeof import('./src/modules/users/store/definition')['userStoreDefinition']
  const validateRoutes: typeof import('./src/utils/routes')['validateRoutes']
  const watch: typeof import('vue')['watch']
  const watchArray: typeof import('@vueuse/core')['watchArray']
  const watchAtMost: typeof import('@vueuse/core')['watchAtMost']
  const watchDebounced: typeof import('@vueuse/core')['watchDebounced']
  const watchDeep: typeof import('@vueuse/core')['watchDeep']
  const watchEffect: typeof import('vue')['watchEffect']
  const watchIgnorable: typeof import('@vueuse/core')['watchIgnorable']
  const watchImmediate: typeof import('@vueuse/core')['watchImmediate']
  const watchOnce: typeof import('@vueuse/core')['watchOnce']
  const watchPausable: typeof import('@vueuse/core')['watchPausable']
  const watchPostEffect: typeof import('vue')['watchPostEffect']
  const watchSyncEffect: typeof import('vue')['watchSyncEffect']
  const watchThrottled: typeof import('@vueuse/core')['watchThrottled']
  const watchTriggerable: typeof import('@vueuse/core')['watchTriggerable']
  const watchWithFilter: typeof import('@vueuse/core')['watchWithFilter']
  const whenever: typeof import('@vueuse/core')['whenever']
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { AppUtils } from './src/utils/index'
  import('./src/utils/index')
  // @ts-ignore
  export type { AppLogger } from './src/utils/logger'
  import('./src/utils/logger')
  // @ts-ignore
  export type { RoutesByPrefix, RoutesInterface } from './src/utils/routes'
  import('./src/utils/routes')
  // @ts-ignore
  export type { ApiResourceModel } from './src/models/ApiResourceModel'
  import('./src/models/ApiResourceModel')
  // @ts-ignore
  export type { GlobalStore } from './src/stores/global/index'
  import('./src/stores/global/index')
  // @ts-ignore
  export type { MachineStore } from './src/modules/machine/store/index'
  import('./src/modules/machine/store/index')
  // @ts-ignore
  export type { OperatorSalaryStore } from './src/modules/operator-salary/store/index'
  import('./src/modules/operator-salary/store/index')
  // @ts-ignore
  export type { OperatorStore } from './src/modules/operator/store/index'
  import('./src/modules/operator/store/index')
  // @ts-ignore
  export type { PermissionStore } from './src/modules/permissions/store/index'
  import('./src/modules/permissions/store/index')
  // @ts-ignore
  export type { RoleStore } from './src/modules/roles/store/index'
  import('./src/modules/roles/store/index')
  // @ts-ignore
  export type { UserStore } from './src/modules/users/store/index'
  import('./src/modules/users/store/index')
  // @ts-ignore
  export type { ApplicationInterface } from './src/modules/applications/interfaces/application_interface'
  import('./src/modules/applications/interfaces/application_interface')
  // @ts-ignore
  export type { ApplicationStoreInterface } from './src/modules/applications/interfaces/application_store_interface'
  import('./src/modules/applications/interfaces/application_store_interface')
  // @ts-ignore
  export type { ForgotPasswordInterface } from './src/modules/authentication/interfaces/forgot_password_interface'
  import('./src/modules/authentication/interfaces/forgot_password_interface')
  // @ts-ignore
  export type { LoginInterface } from './src/modules/authentication/interfaces/login_interface'
  import('./src/modules/authentication/interfaces/login_interface')
  // @ts-ignore
  export type { ResetPasswordInterface } from './src/modules/authentication/interfaces/reset_password_interface'
  import('./src/modules/authentication/interfaces/reset_password_interface')
  // @ts-ignore
  export type { SessionInterface } from './src/modules/authentication/interfaces/session_interface'
  import('./src/modules/authentication/interfaces/session_interface')
  // @ts-ignore
  export type { MachineInterface } from './src/modules/machine/interfaces/machine_interface'
  import('./src/modules/machine/interfaces/machine_interface')
  // @ts-ignore
  export type { MachineCreateInterface } from './src/modules/machine/interfaces/machine_create_interface'
  import('./src/modules/machine/interfaces/machine_create_interface')
  // @ts-ignore
  export type { MachineUpdateInterface } from './src/modules/machine/interfaces/machine_update_interface'
  import('./src/modules/machine/interfaces/machine_update_interface')
  // @ts-ignore
  export type { MachineStoreInterface } from './src/modules/machine/interfaces/machine_store_interface'
  import('./src/modules/machine/interfaces/machine_store_interface')
  // @ts-ignore
  export type { OperatorSalaryInterface } from './src/modules/operator-salary/interfaces/operator_salary_interface'
  import('./src/modules/operator-salary/interfaces/operator_salary_interface')
  // @ts-ignore
  export type { OperatorSalaryCreateInterface } from './src/modules/operator-salary/interfaces/operator_salary_create_interface'
  import('./src/modules/operator-salary/interfaces/operator_salary_create_interface')
  // @ts-ignore
  export type { OperatorSalaryUpdateInterface } from './src/modules/operator-salary/interfaces/operator_salary_update_interface'
  import('./src/modules/operator-salary/interfaces/operator_salary_update_interface')
  // @ts-ignore
  export type { OperatorSalaryStoreInterface } from './src/modules/operator-salary/interfaces/operator_salary_store_interface'
  import('./src/modules/operator-salary/interfaces/operator_salary_store_interface')
  // @ts-ignore
  export type { OperatorSalaryListFilterInterface } from './src/modules/operator-salary/interfaces/operator_salary_list_filter_interface'
  import('./src/modules/operator-salary/interfaces/operator_salary_list_filter_interface')
  // @ts-ignore
  export type { OperatorInterface } from './src/modules/operator/interfaces/operator_interface'
  import('./src/modules/operator/interfaces/operator_interface')
  // @ts-ignore
  export type { OperatorCreateInterface } from './src/modules/operator/interfaces/operator_create_interface'
  import('./src/modules/operator/interfaces/operator_create_interface')
  // @ts-ignore
  export type { OperatorUpdateInterface } from './src/modules/operator/interfaces/operator_update_interface'
  import('./src/modules/operator/interfaces/operator_update_interface')
  // @ts-ignore
  export type { OperatorStoreInterface } from './src/modules/operator/interfaces/operator_store_interface'
  import('./src/modules/operator/interfaces/operator_store_interface')
  // @ts-ignore
  export type { PermissionCreateInterface } from './src/modules/permissions/interfaces/permission_create_interface'
  import('./src/modules/permissions/interfaces/permission_create_interface')
  // @ts-ignore
  export type { PermissionInterface } from './src/modules/permissions/interfaces/permission_interface'
  import('./src/modules/permissions/interfaces/permission_interface')
  // @ts-ignore
  export type { PermissionStoreInterface } from './src/modules/permissions/interfaces/permission_store_interface'
  import('./src/modules/permissions/interfaces/permission_store_interface')
  // @ts-ignore
  export type { PermissionUpdateInterface } from './src/modules/permissions/interfaces/permission_update_interface'
  import('./src/modules/permissions/interfaces/permission_update_interface')
  // @ts-ignore
  export type { RoleInterface } from './src/modules/roles/interfaces/role_interface'
  import('./src/modules/roles/interfaces/role_interface')
  // @ts-ignore
  export type { RoleCreateInterface } from './src/modules/roles/interfaces/role_create_interface'
  import('./src/modules/roles/interfaces/role_create_interface')
  // @ts-ignore
  export type { RoleUpdateInterface } from './src/modules/roles/interfaces/role_update_interface'
  import('./src/modules/roles/interfaces/role_update_interface')
  // @ts-ignore
  export type { RoleStoreInterface } from './src/modules/roles/interfaces/role_store_interface'
  import('./src/modules/roles/interfaces/role_store_interface')
  // @ts-ignore
  export type { UserInterface } from './src/modules/users/interfaces/user_interface'
  import('./src/modules/users/interfaces/user_interface')
  // @ts-ignore
  export type { UserCreateInterface } from './src/modules/users/interfaces/user_create_interface'
  import('./src/modules/users/interfaces/user_create_interface')
  // @ts-ignore
  export type { UserUpdateInterface } from './src/modules/users/interfaces/user_update_interface'
  import('./src/modules/users/interfaces/user_update_interface')
  // @ts-ignore
  export type { UserStoreInterface } from './src/modules/users/interfaces/user_store_interface'
  import('./src/modules/users/interfaces/user_store_interface')
  // @ts-ignore
  export type { UserListFilterInterface } from './src/modules/users/interfaces/user_list_filter_interface'
  import('./src/modules/users/interfaces/user_list_filter_interface')
  // @ts-ignore
  export type { ApplicationModel } from './src/modules/applications/models/application_model'
  import('./src/modules/applications/models/application_model')
  // @ts-ignore
  export type { SessionModel } from './src/modules/authentication/login/models/session_model'
  import('./src/modules/authentication/login/models/session_model')
  // @ts-ignore
  export type { SessionModel } from './src/modules/authentication/models/session_model'
  import('./src/modules/authentication/models/session_model')
  // @ts-ignore
  export type { MachineModel } from './src/modules/machine/models/machine-model'
  import('./src/modules/machine/models/machine-model')
  // @ts-ignore
  export type { OperatorSalaryModel } from './src/modules/operator-salary/models/operator-salary-model'
  import('./src/modules/operator-salary/models/operator-salary-model')
  // @ts-ignore
  export type { OperatorModel } from './src/modules/operator/models/operator-model'
  import('./src/modules/operator/models/operator-model')
  // @ts-ignore
  export type { PermissionModel } from './src/modules/permissions/models/permission_model'
  import('./src/modules/permissions/models/permission_model')
  // @ts-ignore
  export type { RoleModel } from './src/modules/roles/models/role_model'
  import('./src/modules/roles/models/role_model')
  // @ts-ignore
  export type { UserModel } from './src/modules/users/models/user_model'
  import('./src/modules/users/models/user_model')
  // @ts-ignore
  export type { ApiRouteInterface } from './src/api/interfaces/index'
  import('./src/api/interfaces/index')
  // @ts-ignore
  export type { ListApiArgsInterface } from './src/api/interfaces/list_api_args_interface'
  import('./src/api/interfaces/list_api_args_interface')
  // @ts-ignore
  export type { ApiResourceInterface } from './src/interfaces/ApiResourceInterface'
  import('./src/interfaces/ApiResourceInterface')
  // @ts-ignore
  export type { AppAlertType, AppAlertInterface } from './src/interfaces/AppAlertInterface'
  import('./src/interfaces/AppAlertInterface')
  // @ts-ignore
  export type { AppStoreDefinition } from './src/interfaces/app_store_definition_interface'
  import('./src/interfaces/app_store_definition_interface')
  // @ts-ignore
  export type { AppLocalStorage } from './src/services/AppLocalStorage'
  import('./src/services/AppLocalStorage')
  // @ts-ignore
  export type { AppSessionStorage } from './src/services/AppSessionStorage'
  import('./src/services/AppSessionStorage')
  // @ts-ignore
  export type { AppIndexedDBStorage } from './src/services/app_indexed_db_storage'
  import('./src/services/app_indexed_db_storage')
  // @ts-ignore
  export type { AppStorageService, AppStorageOptions } from './src/services/app_storage_service'
  import('./src/services/app_storage_service')
  // @ts-ignore
  export type { GenericStoreService, GenericStoreOptions } from './src/services/generic_store_service'
  import('./src/services/generic_store_service')
  // @ts-ignore
  export type { AppIndexedDBService } from './src/services/indexed_db'
  import('./src/services/indexed_db')
  // @ts-ignore
  export type { AppStoresInterface } from './src/stores/interfaces/app_stores_interface'
  import('./src/stores/interfaces/app_stores_interface')
  // @ts-ignore
  export type { GlobalStoreInterface } from './src/stores/interfaces/global_store_interface'
  import('./src/stores/interfaces/global_store_interface')
  // @ts-ignore
  export type { StoreInterface } from './src/stores/interfaces/store_interface'
  import('./src/stores/interfaces/store_interface')
  // @ts-ignore
  export type { TemplateSettingsInterface } from './src/stores/interfaces/template_settings_interface'
  import('./src/stores/interfaces/template_settings_interface')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly ApiResourceModel: UnwrapRef<typeof import('./src/models/ApiResourceModel')['ApiResourceModel']>
    readonly AppIndexedDBService: UnwrapRef<typeof import('./src/services/indexed_db')['AppIndexedDBService']>
    readonly AppIndexedDBStorage: UnwrapRef<typeof import('./src/services/app_indexed_db_storage')['AppIndexedDBStorage']>
    readonly AppLocalStorage: UnwrapRef<typeof import('./src/services/AppLocalStorage')['default']>
    readonly AppLogger: UnwrapRef<typeof import('./src/utils/logger')['AppLogger']>
    readonly AppSessionStorage: UnwrapRef<typeof import('./src/services/AppSessionStorage')['default']>
    readonly AppStorageService: UnwrapRef<typeof import('./src/services/app_storage_service')['AppStorageService']>
    readonly AppUtils: UnwrapRef<typeof import('./src/utils/index')['AppUtils']>
    readonly ApplicationModel: UnwrapRef<typeof import('./src/modules/applications/models/application_model')['ApplicationModel']>
    readonly DateTime: UnwrapRef<typeof import('./src/utils/luxon')['DateTime']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly GenericStoreService: UnwrapRef<typeof import('./src/services/generic_store_service')['GenericStoreService']>
    readonly MachineModel: UnwrapRef<typeof import('./src/modules/machine/models/machine-model')['MachineModel']>
    readonly OperatorModel: UnwrapRef<typeof import('./src/modules/operator/models/operator-model')['OperatorModel']>
    readonly OperatorSalaryModel: UnwrapRef<typeof import('./src/modules/operator-salary/models/operator-salary-model')['OperatorSalaryModel']>
    readonly PermissionModel: UnwrapRef<typeof import('./src/modules/permissions/models/permission_model')['PermissionModel']>
    readonly RoleModel: UnwrapRef<typeof import('./src/modules/roles/models/role_model')['RoleModel']>
    readonly SessionModel: UnwrapRef<typeof import('./src/modules/authentication/models/session_model')['SessionModel']>
    readonly UserModel: UnwrapRef<typeof import('./src/modules/users/models/user_model')['UserModel']>
    readonly acceptHMRUpdate: UnwrapRef<typeof import('pinia')['acceptHMRUpdate']>
    readonly apiRouteInterface: UnwrapRef<typeof import('./src/api/interfaces/api_route_interface')['default']>
    readonly appIndexedDbStorage: UnwrapRef<typeof import('./src/services/app_indexed_db_storage')['default']>
    readonly appLogger: UnwrapRef<typeof import('./src/utils/logger')['appLogger']>
    readonly appRoutes: UnwrapRef<typeof import('./src/router/routes')['appRoutes']>
    readonly asyncComputed: UnwrapRef<typeof import('@vueuse/core')['asyncComputed']>
    readonly autoResetRef: UnwrapRef<typeof import('@vueuse/core')['autoResetRef']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly computedAsync: UnwrapRef<typeof import('@vueuse/core')['computedAsync']>
    readonly computedEager: UnwrapRef<typeof import('@vueuse/core')['computedEager']>
    readonly computedInject: UnwrapRef<typeof import('@vueuse/core')['computedInject']>
    readonly computedWithControl: UnwrapRef<typeof import('@vueuse/core')['computedWithControl']>
    readonly controlledComputed: UnwrapRef<typeof import('@vueuse/core')['controlledComputed']>
    readonly controlledRef: UnwrapRef<typeof import('@vueuse/core')['controlledRef']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly createEventHook: UnwrapRef<typeof import('@vueuse/core')['createEventHook']>
    readonly createGenericProjection: UnwrapRef<typeof import('@vueuse/math')['createGenericProjection']>
    readonly createGlobalState: UnwrapRef<typeof import('@vueuse/core')['createGlobalState']>
    readonly createInjectionState: UnwrapRef<typeof import('@vueuse/core')['createInjectionState']>
    readonly createLogger: UnwrapRef<typeof import('./src/utils/logger')['createLogger']>
    readonly createPinia: UnwrapRef<typeof import('pinia')['createPinia']>
    readonly createProjection: UnwrapRef<typeof import('@vueuse/math')['createProjection']>
    readonly createReactiveFn: UnwrapRef<typeof import('@vueuse/core')['createReactiveFn']>
    readonly createRef: UnwrapRef<typeof import('@vueuse/core')['createRef']>
    readonly createReusableTemplate: UnwrapRef<typeof import('@vueuse/core')['createReusableTemplate']>
    readonly createRoutes: UnwrapRef<typeof import('./src/utils/routes')['createRoutes']>
    readonly createSharedComposable: UnwrapRef<typeof import('@vueuse/core')['createSharedComposable']>
    readonly createTemplatePromise: UnwrapRef<typeof import('@vueuse/core')['createTemplatePromise']>
    readonly createUnrefFn: UnwrapRef<typeof import('@vueuse/core')['createUnrefFn']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly debouncedRef: UnwrapRef<typeof import('@vueuse/core')['debouncedRef']>
    readonly debouncedWatch: UnwrapRef<typeof import('@vueuse/core')['debouncedWatch']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly defineStore: UnwrapRef<typeof import('pinia')['defineStore']>
    readonly eagerComputed: UnwrapRef<typeof import('@vueuse/core')['eagerComputed']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly extendRef: UnwrapRef<typeof import('@vueuse/core')['extendRef']>
    readonly extractMonthAndYear: UnwrapRef<typeof import('./src/utils/formatDate')['extractMonthAndYear']>
    readonly formIsValid: UnwrapRef<typeof import('./src/utils/form_is_valid')['formIsValid']>
    readonly formatPhoneWithSpaces: UnwrapRef<typeof import('./src/utils/remove_white_space')['formatPhoneWithSpaces']>
    readonly getActivePinia: UnwrapRef<typeof import('pinia')['getActivePinia']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly globalStoreDefinition: UnwrapRef<typeof import('./src/stores/global/definition')['globalStoreDefinition']>
    readonly guestRoutes: UnwrapRef<typeof import('./src/router/routes')['guestRoutes']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly hexToRgba: UnwrapRef<typeof import('./src/utils/hex_to_rgba')['hexToRgba']>
    readonly ignorableWatch: UnwrapRef<typeof import('@vueuse/core')['ignorableWatch']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly injectLocal: UnwrapRef<typeof import('@vueuse/core')['injectLocal']>
    readonly isDefined: UnwrapRef<typeof import('@vueuse/core')['isDefined']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly logicAnd: UnwrapRef<typeof import('@vueuse/math')['logicAnd']>
    readonly logicNot: UnwrapRef<typeof import('@vueuse/math')['logicNot']>
    readonly logicOr: UnwrapRef<typeof import('@vueuse/math')['logicOr']>
    readonly luxonFormats: UnwrapRef<typeof import('./src/utils/luxon')['luxonFormats']>
    readonly machineStoreDefinition: UnwrapRef<typeof import('./src/modules/machine/store/definition')['machineStoreDefinition']>
    readonly makeDestructurable: UnwrapRef<typeof import('@vueuse/core')['makeDestructurable']>
    readonly mapActions: UnwrapRef<typeof import('pinia')['mapActions']>
    readonly mapGetters: UnwrapRef<typeof import('pinia')['mapGetters']>
    readonly mapState: UnwrapRef<typeof import('pinia')['mapState']>
    readonly mapStores: UnwrapRef<typeof import('pinia')['mapStores']>
    readonly mapWritableState: UnwrapRef<typeof import('pinia')['mapWritableState']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly numberFormatter: UnwrapRef<typeof import('./src/utils/number_formatter')['numberFormatter']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onClickOutside: UnwrapRef<typeof import('@vueuse/core')['onClickOutside']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onElementRemoval: UnwrapRef<typeof import('@vueuse/core')['onElementRemoval']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onKeyStroke: UnwrapRef<typeof import('@vueuse/core')['onKeyStroke']>
    readonly onLongPress: UnwrapRef<typeof import('@vueuse/core')['onLongPress']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onStartTyping: UnwrapRef<typeof import('@vueuse/core')['onStartTyping']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly operatorSalaryStoreDefinition: UnwrapRef<typeof import('./src/modules/operator-salary/store/definition')['operatorSalaryStoreDefinition']>
    readonly operatorStoreDefinition: UnwrapRef<typeof import('./src/modules/operator/store/definition')['operatorStoreDefinition']>
    readonly pausableWatch: UnwrapRef<typeof import('@vueuse/core')['pausableWatch']>
    readonly permissionStoreDefinition: UnwrapRef<typeof import('./src/modules/permissions/store/index')['permissionStoreDefinition']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly provideLocal: UnwrapRef<typeof import('@vueuse/core')['provideLocal']>
    readonly reactify: UnwrapRef<typeof import('@vueuse/core')['reactify']>
    readonly reactifyObject: UnwrapRef<typeof import('@vueuse/core')['reactifyObject']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly reactiveComputed: UnwrapRef<typeof import('@vueuse/core')['reactiveComputed']>
    readonly reactiveOmit: UnwrapRef<typeof import('@vueuse/core')['reactiveOmit']>
    readonly reactivePick: UnwrapRef<typeof import('@vueuse/core')['reactivePick']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly refAutoReset: UnwrapRef<typeof import('@vueuse/core')['refAutoReset']>
    readonly refDebounced: UnwrapRef<typeof import('@vueuse/core')['refDebounced']>
    readonly refDefault: UnwrapRef<typeof import('@vueuse/core')['refDefault']>
    readonly refThrottled: UnwrapRef<typeof import('@vueuse/core')['refThrottled']>
    readonly refWithControl: UnwrapRef<typeof import('@vueuse/core')['refWithControl']>
    readonly registerPlugins: UnwrapRef<typeof import('./src/router/index')['registerPlugins']>
    readonly removeWhitespace: UnwrapRef<typeof import('./src/utils/remove_white_space')['removeWhitespace']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly resolveRef: UnwrapRef<typeof import('@vueuse/core')['resolveRef']>
    readonly resolveUnref: UnwrapRef<typeof import('@vueuse/core')['resolveUnref']>
    readonly roleStoreDefinition: UnwrapRef<typeof import('./src/modules/roles/store/definition')['roleStoreDefinition']>
    readonly router: UnwrapRef<typeof import('./src/router/index')['default']>
    readonly routes: UnwrapRef<typeof import('./src/router/routes')['default']>
    readonly sessionInterface: UnwrapRef<typeof import('./src/modules/authentication/login/interfaces/session_interface')['default']>
    readonly sessionModel: UnwrapRef<typeof import('./src/modules/authentication/login/models/session_model')['default']>
    readonly setActivePinia: UnwrapRef<typeof import('pinia')['setActivePinia']>
    readonly setMapStoreSuffix: UnwrapRef<typeof import('pinia')['setMapStoreSuffix']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly showAlert: UnwrapRef<typeof import('./src/utils/show_alert')['showAlert']>
    readonly starter: UnwrapRef<typeof import('./src/router/starter')['default']>
    readonly storeToRefs: UnwrapRef<typeof import('pinia')['storeToRefs']>
    readonly syncRef: UnwrapRef<typeof import('@vueuse/core')['syncRef']>
    readonly syncRefs: UnwrapRef<typeof import('@vueuse/core')['syncRefs']>
    readonly templateRef: UnwrapRef<typeof import('@vueuse/core')['templateRef']>
    readonly throttledRef: UnwrapRef<typeof import('@vueuse/core')['throttledRef']>
    readonly throttledWatch: UnwrapRef<typeof import('@vueuse/core')['throttledWatch']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toReactive: UnwrapRef<typeof import('@vueuse/core')['toReactive']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly toast: UnwrapRef<typeof import('./src/utils/toast')['toast']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly tryOnBeforeMount: UnwrapRef<typeof import('@vueuse/core')['tryOnBeforeMount']>
    readonly tryOnBeforeUnmount: UnwrapRef<typeof import('@vueuse/core')['tryOnBeforeUnmount']>
    readonly tryOnMounted: UnwrapRef<typeof import('@vueuse/core')['tryOnMounted']>
    readonly tryOnScopeDispose: UnwrapRef<typeof import('@vueuse/core')['tryOnScopeDispose']>
    readonly tryOnUnmounted: UnwrapRef<typeof import('@vueuse/core')['tryOnUnmounted']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly unrefElement: UnwrapRef<typeof import('@vueuse/core')['unrefElement']>
    readonly until: UnwrapRef<typeof import('@vueuse/core')['until']>
    readonly useAbs: UnwrapRef<typeof import('@vueuse/math')['useAbs']>
    readonly useActiveElement: UnwrapRef<typeof import('@vueuse/core')['useActiveElement']>
    readonly useAnimate: UnwrapRef<typeof import('@vueuse/core')['useAnimate']>
    readonly useArrayDifference: UnwrapRef<typeof import('@vueuse/core')['useArrayDifference']>
    readonly useArrayEvery: UnwrapRef<typeof import('@vueuse/core')['useArrayEvery']>
    readonly useArrayFilter: UnwrapRef<typeof import('@vueuse/core')['useArrayFilter']>
    readonly useArrayFind: UnwrapRef<typeof import('@vueuse/core')['useArrayFind']>
    readonly useArrayFindIndex: UnwrapRef<typeof import('@vueuse/core')['useArrayFindIndex']>
    readonly useArrayFindLast: UnwrapRef<typeof import('@vueuse/core')['useArrayFindLast']>
    readonly useArrayIncludes: UnwrapRef<typeof import('@vueuse/core')['useArrayIncludes']>
    readonly useArrayJoin: UnwrapRef<typeof import('@vueuse/core')['useArrayJoin']>
    readonly useArrayMap: UnwrapRef<typeof import('@vueuse/core')['useArrayMap']>
    readonly useArrayReduce: UnwrapRef<typeof import('@vueuse/core')['useArrayReduce']>
    readonly useArraySome: UnwrapRef<typeof import('@vueuse/core')['useArraySome']>
    readonly useArrayUnique: UnwrapRef<typeof import('@vueuse/core')['useArrayUnique']>
    readonly useAsyncQueue: UnwrapRef<typeof import('@vueuse/core')['useAsyncQueue']>
    readonly useAsyncState: UnwrapRef<typeof import('@vueuse/core')['useAsyncState']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useAverage: UnwrapRef<typeof import('@vueuse/math')['useAverage']>
    readonly useBase64: UnwrapRef<typeof import('@vueuse/core')['useBase64']>
    readonly useBattery: UnwrapRef<typeof import('@vueuse/core')['useBattery']>
    readonly useBluetooth: UnwrapRef<typeof import('@vueuse/core')['useBluetooth']>
    readonly useBreakpoints: UnwrapRef<typeof import('@vueuse/core')['useBreakpoints']>
    readonly useBroadcastChannel: UnwrapRef<typeof import('@vueuse/core')['useBroadcastChannel']>
    readonly useBrowserLocation: UnwrapRef<typeof import('@vueuse/core')['useBrowserLocation']>
    readonly useCached: UnwrapRef<typeof import('@vueuse/core')['useCached']>
    readonly useCeil: UnwrapRef<typeof import('@vueuse/math')['useCeil']>
    readonly useClamp: UnwrapRef<typeof import('@vueuse/math')['useClamp']>
    readonly useClipboard: UnwrapRef<typeof import('@vueuse/core')['useClipboard']>
    readonly useClipboardItems: UnwrapRef<typeof import('@vueuse/core')['useClipboardItems']>
    readonly useCloned: UnwrapRef<typeof import('@vueuse/core')['useCloned']>
    readonly useColorMode: UnwrapRef<typeof import('@vueuse/core')['useColorMode']>
    readonly useConfirmDialog: UnwrapRef<typeof import('@vueuse/core')['useConfirmDialog']>
    readonly useCountdown: UnwrapRef<typeof import('@vueuse/core')['useCountdown']>
    readonly useCounter: UnwrapRef<typeof import('@vueuse/core')['useCounter']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVar: UnwrapRef<typeof import('@vueuse/core')['useCssVar']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useCurrentElement: UnwrapRef<typeof import('@vueuse/core')['useCurrentElement']>
    readonly useCycleList: UnwrapRef<typeof import('@vueuse/core')['useCycleList']>
    readonly useDark: UnwrapRef<typeof import('@vueuse/core')['useDark']>
    readonly useDateFormat: UnwrapRef<typeof import('@vueuse/core')['useDateFormat']>
    readonly useDebounce: UnwrapRef<typeof import('@vueuse/core')['useDebounce']>
    readonly useDebounceFn: UnwrapRef<typeof import('@vueuse/core')['useDebounceFn']>
    readonly useDebouncedRefHistory: UnwrapRef<typeof import('@vueuse/core')['useDebouncedRefHistory']>
    readonly useDeviceMotion: UnwrapRef<typeof import('@vueuse/core')['useDeviceMotion']>
    readonly useDeviceOrientation: UnwrapRef<typeof import('@vueuse/core')['useDeviceOrientation']>
    readonly useDevicePixelRatio: UnwrapRef<typeof import('@vueuse/core')['useDevicePixelRatio']>
    readonly useDevicesList: UnwrapRef<typeof import('@vueuse/core')['useDevicesList']>
    readonly useDisplayMedia: UnwrapRef<typeof import('@vueuse/core')['useDisplayMedia']>
    readonly useDocumentVisibility: UnwrapRef<typeof import('@vueuse/core')['useDocumentVisibility']>
    readonly useDraggable: UnwrapRef<typeof import('@vueuse/core')['useDraggable']>
    readonly useDropZone: UnwrapRef<typeof import('@vueuse/core')['useDropZone']>
    readonly useElementBounding: UnwrapRef<typeof import('@vueuse/core')['useElementBounding']>
    readonly useElementByPoint: UnwrapRef<typeof import('@vueuse/core')['useElementByPoint']>
    readonly useElementHover: UnwrapRef<typeof import('@vueuse/core')['useElementHover']>
    readonly useElementSize: UnwrapRef<typeof import('@vueuse/core')['useElementSize']>
    readonly useElementVisibility: UnwrapRef<typeof import('@vueuse/core')['useElementVisibility']>
    readonly useEventBus: UnwrapRef<typeof import('@vueuse/core')['useEventBus']>
    readonly useEventListener: UnwrapRef<typeof import('@vueuse/core')['useEventListener']>
    readonly useEventSource: UnwrapRef<typeof import('@vueuse/core')['useEventSource']>
    readonly useEyeDropper: UnwrapRef<typeof import('@vueuse/core')['useEyeDropper']>
    readonly useFavicon: UnwrapRef<typeof import('@vueuse/core')['useFavicon']>
    readonly useFetch: UnwrapRef<typeof import('@vueuse/core')['useFetch']>
    readonly useFileDialog: UnwrapRef<typeof import('@vueuse/core')['useFileDialog']>
    readonly useFileSystemAccess: UnwrapRef<typeof import('@vueuse/core')['useFileSystemAccess']>
    readonly useFloor: UnwrapRef<typeof import('@vueuse/math')['useFloor']>
    readonly useFocus: UnwrapRef<typeof import('@vueuse/core')['useFocus']>
    readonly useFocusWithin: UnwrapRef<typeof import('@vueuse/core')['useFocusWithin']>
    readonly useFps: UnwrapRef<typeof import('@vueuse/core')['useFps']>
    readonly useFullscreen: UnwrapRef<typeof import('@vueuse/core')['useFullscreen']>
    readonly useGamepad: UnwrapRef<typeof import('@vueuse/core')['useGamepad']>
    readonly useGeolocation: UnwrapRef<typeof import('@vueuse/core')['useGeolocation']>
    readonly useGlobalStore: UnwrapRef<typeof import('./src/stores/global/index')['useGlobalStore']>
    readonly useI18n: UnwrapRef<typeof import('vue-i18n')['useI18n']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useIdle: UnwrapRef<typeof import('@vueuse/core')['useIdle']>
    readonly useImage: UnwrapRef<typeof import('@vueuse/core')['useImage']>
    readonly useInfiniteScroll: UnwrapRef<typeof import('@vueuse/core')['useInfiniteScroll']>
    readonly useInitializedGlobalStore: UnwrapRef<typeof import('./src/stores/global/index')['useInitializedGlobalStore']>
    readonly useInitializedMachineStore: UnwrapRef<typeof import('./src/modules/machine/store/index')['useInitializedMachineStore']>
    readonly useInitializedOperatorSalaryStore: UnwrapRef<typeof import('./src/modules/operator-salary/store/index')['useInitializedOperatorSalaryStore']>
    readonly useInitializedOperatorStore: UnwrapRef<typeof import('./src/modules/operator/store/index')['useInitializedOperatorStore']>
    readonly useInitializedPermissionStore: UnwrapRef<typeof import('./src/modules/permissions/store/index')['useInitializedPermissionStore']>
    readonly useInitializedRoleStore: UnwrapRef<typeof import('./src/modules/roles/store/index')['useInitializedRoleStore']>
    readonly useInitializedUserStore: UnwrapRef<typeof import('./src/modules/users/store/index')['useInitializedUserStore']>
    readonly useIntersectionObserver: UnwrapRef<typeof import('@vueuse/core')['useIntersectionObserver']>
    readonly useInterval: UnwrapRef<typeof import('@vueuse/core')['useInterval']>
    readonly useIntervalFn: UnwrapRef<typeof import('@vueuse/core')['useIntervalFn']>
    readonly useKeyModifier: UnwrapRef<typeof import('@vueuse/core')['useKeyModifier']>
    readonly useLastChanged: UnwrapRef<typeof import('@vueuse/core')['useLastChanged']>
    readonly useLocalStorage: UnwrapRef<typeof import('@vueuse/core')['useLocalStorage']>
    readonly useMagicKeys: UnwrapRef<typeof import('@vueuse/core')['useMagicKeys']>
    readonly useManualRefHistory: UnwrapRef<typeof import('@vueuse/core')['useManualRefHistory']>
    readonly useMath: UnwrapRef<typeof import('@vueuse/math')['useMath']>
    readonly useMax: UnwrapRef<typeof import('@vueuse/math')['useMax']>
    readonly useMediaControls: UnwrapRef<typeof import('@vueuse/core')['useMediaControls']>
    readonly useMediaQuery: UnwrapRef<typeof import('@vueuse/core')['useMediaQuery']>
    readonly useMemoize: UnwrapRef<typeof import('@vueuse/core')['useMemoize']>
    readonly useMemory: UnwrapRef<typeof import('@vueuse/core')['useMemory']>
    readonly useMin: UnwrapRef<typeof import('@vueuse/math')['useMin']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly useMounted: UnwrapRef<typeof import('@vueuse/core')['useMounted']>
    readonly useMouse: UnwrapRef<typeof import('@vueuse/core')['useMouse']>
    readonly useMouseInElement: UnwrapRef<typeof import('@vueuse/core')['useMouseInElement']>
    readonly useMousePressed: UnwrapRef<typeof import('@vueuse/core')['useMousePressed']>
    readonly useMutationObserver: UnwrapRef<typeof import('@vueuse/core')['useMutationObserver']>
    readonly useNavigatorLanguage: UnwrapRef<typeof import('@vueuse/core')['useNavigatorLanguage']>
    readonly useNetwork: UnwrapRef<typeof import('@vueuse/core')['useNetwork']>
    readonly useNow: UnwrapRef<typeof import('@vueuse/core')['useNow']>
    readonly useObjectUrl: UnwrapRef<typeof import('@vueuse/core')['useObjectUrl']>
    readonly useOffsetPagination: UnwrapRef<typeof import('@vueuse/core')['useOffsetPagination']>
    readonly useOnline: UnwrapRef<typeof import('@vueuse/core')['useOnline']>
    readonly usePageLeave: UnwrapRef<typeof import('@vueuse/core')['usePageLeave']>
    readonly useParallax: UnwrapRef<typeof import('@vueuse/core')['useParallax']>
    readonly useParentElement: UnwrapRef<typeof import('@vueuse/core')['useParentElement']>
    readonly usePerformanceObserver: UnwrapRef<typeof import('@vueuse/core')['usePerformanceObserver']>
    readonly usePermission: UnwrapRef<typeof import('@vueuse/core')['usePermission']>
    readonly usePointer: UnwrapRef<typeof import('@vueuse/core')['usePointer']>
    readonly usePointerLock: UnwrapRef<typeof import('@vueuse/core')['usePointerLock']>
    readonly usePointerSwipe: UnwrapRef<typeof import('@vueuse/core')['usePointerSwipe']>
    readonly usePrecision: UnwrapRef<typeof import('@vueuse/math')['usePrecision']>
    readonly usePreferredColorScheme: UnwrapRef<typeof import('@vueuse/core')['usePreferredColorScheme']>
    readonly usePreferredContrast: UnwrapRef<typeof import('@vueuse/core')['usePreferredContrast']>
    readonly usePreferredDark: UnwrapRef<typeof import('@vueuse/core')['usePreferredDark']>
    readonly usePreferredLanguages: UnwrapRef<typeof import('@vueuse/core')['usePreferredLanguages']>
    readonly usePreferredReducedMotion: UnwrapRef<typeof import('@vueuse/core')['usePreferredReducedMotion']>
    readonly usePreferredReducedTransparency: UnwrapRef<typeof import('@vueuse/core')['usePreferredReducedTransparency']>
    readonly usePrevious: UnwrapRef<typeof import('@vueuse/core')['usePrevious']>
    readonly useProjection: UnwrapRef<typeof import('@vueuse/math')['useProjection']>
    readonly useRafFn: UnwrapRef<typeof import('@vueuse/core')['useRafFn']>
    readonly useRefHistory: UnwrapRef<typeof import('@vueuse/core')['useRefHistory']>
    readonly useResizeObserver: UnwrapRef<typeof import('@vueuse/core')['useResizeObserver']>
    readonly useRound: UnwrapRef<typeof import('@vueuse/math')['useRound']>
    readonly useSSRWidth: UnwrapRef<typeof import('@vueuse/core')['useSSRWidth']>
    readonly useScreenOrientation: UnwrapRef<typeof import('@vueuse/core')['useScreenOrientation']>
    readonly useScreenSafeArea: UnwrapRef<typeof import('@vueuse/core')['useScreenSafeArea']>
    readonly useScriptTag: UnwrapRef<typeof import('@vueuse/core')['useScriptTag']>
    readonly useScroll: UnwrapRef<typeof import('@vueuse/core')['useScroll']>
    readonly useScrollLock: UnwrapRef<typeof import('@vueuse/core')['useScrollLock']>
    readonly useSessionStorage: UnwrapRef<typeof import('@vueuse/core')['useSessionStorage']>
    readonly useShare: UnwrapRef<typeof import('@vueuse/core')['useShare']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useSorted: UnwrapRef<typeof import('@vueuse/core')['useSorted']>
    readonly useSpeechRecognition: UnwrapRef<typeof import('@vueuse/core')['useSpeechRecognition']>
    readonly useSpeechSynthesis: UnwrapRef<typeof import('@vueuse/core')['useSpeechSynthesis']>
    readonly useStepper: UnwrapRef<typeof import('@vueuse/core')['useStepper']>
    readonly useStorage: UnwrapRef<typeof import('@vueuse/core')['useStorage']>
    readonly useStorageAsync: UnwrapRef<typeof import('@vueuse/core')['useStorageAsync']>
    readonly useStyleTag: UnwrapRef<typeof import('@vueuse/core')['useStyleTag']>
    readonly useSum: UnwrapRef<typeof import('@vueuse/math')['useSum']>
    readonly useSupported: UnwrapRef<typeof import('@vueuse/core')['useSupported']>
    readonly useSwipe: UnwrapRef<typeof import('@vueuse/core')['useSwipe']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useTemplateRefsList: UnwrapRef<typeof import('@vueuse/core')['useTemplateRefsList']>
    readonly useTextDirection: UnwrapRef<typeof import('@vueuse/core')['useTextDirection']>
    readonly useTextSelection: UnwrapRef<typeof import('@vueuse/core')['useTextSelection']>
    readonly useTextareaAutosize: UnwrapRef<typeof import('@vueuse/core')['useTextareaAutosize']>
    readonly useThrottle: UnwrapRef<typeof import('@vueuse/core')['useThrottle']>
    readonly useThrottleFn: UnwrapRef<typeof import('@vueuse/core')['useThrottleFn']>
    readonly useThrottledRefHistory: UnwrapRef<typeof import('@vueuse/core')['useThrottledRefHistory']>
    readonly useTimeAgo: UnwrapRef<typeof import('@vueuse/core')['useTimeAgo']>
    readonly useTimeAgoIntl: UnwrapRef<typeof import('@vueuse/core')['useTimeAgoIntl']>
    readonly useTimeout: UnwrapRef<typeof import('@vueuse/core')['useTimeout']>
    readonly useTimeoutFn: UnwrapRef<typeof import('@vueuse/core')['useTimeoutFn']>
    readonly useTimeoutPoll: UnwrapRef<typeof import('@vueuse/core')['useTimeoutPoll']>
    readonly useTimestamp: UnwrapRef<typeof import('@vueuse/core')['useTimestamp']>
    readonly useTitle: UnwrapRef<typeof import('@vueuse/core')['useTitle']>
    readonly useToNumber: UnwrapRef<typeof import('@vueuse/core')['useToNumber']>
    readonly useToString: UnwrapRef<typeof import('@vueuse/core')['useToString']>
    readonly useToggle: UnwrapRef<typeof import('@vueuse/core')['useToggle']>
    readonly useTransition: UnwrapRef<typeof import('@vueuse/core')['useTransition']>
    readonly useTrunc: UnwrapRef<typeof import('@vueuse/math')['useTrunc']>
    readonly useUrlSearchParams: UnwrapRef<typeof import('@vueuse/core')['useUrlSearchParams']>
    readonly useUserMedia: UnwrapRef<typeof import('@vueuse/core')['useUserMedia']>
    readonly useVModel: UnwrapRef<typeof import('@vueuse/core')['useVModel']>
    readonly useVModels: UnwrapRef<typeof import('@vueuse/core')['useVModels']>
    readonly useVibrate: UnwrapRef<typeof import('@vueuse/core')['useVibrate']>
    readonly useVirtualList: UnwrapRef<typeof import('@vueuse/core')['useVirtualList']>
    readonly useWakeLock: UnwrapRef<typeof import('@vueuse/core')['useWakeLock']>
    readonly useWebNotification: UnwrapRef<typeof import('@vueuse/core')['useWebNotification']>
    readonly useWebSocket: UnwrapRef<typeof import('@vueuse/core')['useWebSocket']>
    readonly useWebWorker: UnwrapRef<typeof import('@vueuse/core')['useWebWorker']>
    readonly useWebWorkerFn: UnwrapRef<typeof import('@vueuse/core')['useWebWorkerFn']>
    readonly useWindowFocus: UnwrapRef<typeof import('@vueuse/core')['useWindowFocus']>
    readonly useWindowScroll: UnwrapRef<typeof import('@vueuse/core')['useWindowScroll']>
    readonly useWindowSize: UnwrapRef<typeof import('@vueuse/core')['useWindowSize']>
    readonly userStoreDefinition: UnwrapRef<typeof import('./src/modules/users/store/definition')['userStoreDefinition']>
    readonly validateRoutes: UnwrapRef<typeof import('./src/utils/routes')['validateRoutes']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchArray: UnwrapRef<typeof import('@vueuse/core')['watchArray']>
    readonly watchAtMost: UnwrapRef<typeof import('@vueuse/core')['watchAtMost']>
    readonly watchDebounced: UnwrapRef<typeof import('@vueuse/core')['watchDebounced']>
    readonly watchDeep: UnwrapRef<typeof import('@vueuse/core')['watchDeep']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchIgnorable: UnwrapRef<typeof import('@vueuse/core')['watchIgnorable']>
    readonly watchImmediate: UnwrapRef<typeof import('@vueuse/core')['watchImmediate']>
    readonly watchOnce: UnwrapRef<typeof import('@vueuse/core')['watchOnce']>
    readonly watchPausable: UnwrapRef<typeof import('@vueuse/core')['watchPausable']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
    readonly watchThrottled: UnwrapRef<typeof import('@vueuse/core')['watchThrottled']>
    readonly watchTriggerable: UnwrapRef<typeof import('@vueuse/core')['watchTriggerable']>
    readonly watchWithFilter: UnwrapRef<typeof import('@vueuse/core')['watchWithFilter']>
    readonly whenever: UnwrapRef<typeof import('@vueuse/core')['whenever']>
  }
}