/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./src/components/Alert.vue')['default']
    AppAlerts: typeof import('./src/components/AppAlerts.vue')['default']
    AppI18n: typeof import('./src/components/AppI18n.vue')['default']
    AppList: typeof import('./src/modules/applications/views/AppList.vue')['default']
    AppLoader: typeof import('./src/components/AppLoader.vue')['default']
    BaseBackground: typeof import('./src/components/BaseBackground.vue')['default']
    BaseBlock: typeof import('./src/components/BaseBlock.vue')['default']
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    BaseNavigation: typeof import('./src/components/BaseNavigation.vue')['default']
    BasePageHeading: typeof import('./src/components/BasePageHeading.vue')['default']
    ComingSoon: typeof import('./src/components/ComingSoon.vue')['default']
    CustomTable: typeof import('./src/components/CustomTable.vue')['default']
    HeaderSearchForm: typeof import('./src/components/HeaderSearchForm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginForm: typeof import('./src/modules/authentication/login/views/LoginForm.vue')['default']
    MachineAddView: typeof import('./src/modules/machine/views/MachineAddView.vue')['default']
    MachineEditView: typeof import('./src/modules/machine/views/MachineEditView.vue')['default']
    MachineForm: typeof import('./src/modules/machine/components/MachineForm.vue')['default']
    MachineListView: typeof import('./src/modules/machine/views/MachineListView.vue')['default']
    OperatorAddView: typeof import('./src/modules/operator/views/OperatorAddView.vue')['default']
    OperatorCalculateSalaryView: typeof import('./src/modules/operator-salary/views/OperatorCalculateSalaryView.vue')['default']
    OperatorEditView: typeof import('./src/modules/operator/views/OperatorEditView.vue')['default']
    OperatorForm: typeof import('./src/modules/operator/components/OperatorForm.vue')['default']
    OperatorListView: typeof import('./src/modules/operator/views/OperatorListView.vue')['default']
    OperatorSalaryDetailsView: typeof import('./src/modules/operator-salary/views/OperatorSalaryDetailsView.vue')['default']
    OperatorSalaryEditView: typeof import('./src/modules/operator-salary/views/OperatorSalaryEditView.vue')['default']
    OperatorSalaryForm: typeof import('./src/modules/operator-salary/components/OperatorSalaryForm.vue')['default']
    OperatorSalaryListView: typeof import('./src/modules/operator-salary/views/OperatorSalaryListView.vue')['default']
    RichTextField: typeof import('./src/components/RichTextField.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackBar: typeof import('./src/components/SnackBar.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    ThemeSwitcher2: typeof import('./src/components/ThemeSwitcher2.vue')['default']
    Tooltip: typeof import('./src/components/Tooltip.vue')['default']
    UserAddView: typeof import('./src/modules/users/views/UserAddView.vue')['default']
    UserEditView: typeof import('./src/modules/users/views/UserEditView.vue')['default']
    UserForm: typeof import('./src/modules/users/components/UserForm.vue')['default']
    UserListView: typeof import('./src/modules/users/views/UserListView.vue')['default']
  }
}
