/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppList: typeof import('./src/modules/applications/views/AppList.vue')['default']
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoginForm: typeof import('./src/modules/authentication/login/views/LoginForm.vue')['default']
    MachineAddView: typeof import('./src/modules/machine/views/MachineAddView.vue')['default']
    MachineEditView: typeof import('./src/modules/machine/views/MachineEditView.vue')['default']
    MachineForm: typeof import('./src/modules/machine/components/MachineForm.vue')['default']
    MachineListView: typeof import('./src/modules/machine/views/MachineListView.vue')['default']
    OperatorAddView: typeof import('./src/modules/operator/views/OperatorAddView.vue')['default']
    OperatorEditView: typeof import('./src/modules/operator/views/OperatorEditView.vue')['default']
    OperatorForm: typeof import('./src/modules/operator/components/OperatorForm.vue')['default']
    OperatorListView: typeof import('./src/modules/operator/views/OperatorListView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tooltip: typeof import('./src/components/Tooltip.vue')['default']
    UserAddView: typeof import('./src/modules/users/views/UserAddView.vue')['default']
    UserEditView: typeof import('./src/modules/users/views/UserEditView.vue')['default']
    UserForm: typeof import('./src/modules/users/components/UserForm.vue')['default']
    UserListView: typeof import('./src/modules/users/views/UserListView.vue')['default']
  }
}
